### ISSUE TITLE
lxc-iptag file missing after installation

### ISSUE THREAD

**Issue by TvT73** [gitsang/lxc-iptag#1]
Hi,
I found your script and tried to test it.

I am on 8.2.4 but after using your script the nano /usr/local/bin/lxc-iptag shows an empty file. 
Shall I only copy the file from here and change the IP Adress to the range of my setup?

Trying only to download the script install.sh is also not possible. Seems taht nothing has been installed.

Okay, my vault. I have no dns anymore after changing the ip of proxmox server.

**Comment by TvT73** [comment]
works like a charm :-)

**Comment by gitsang** [comment]
Sorry I can't reproduce your issue, but I'm glad you've already solved it yourself.
